// 광고 매체(media) 전 컬럼 폼 필드 정의 — 백엔드 media 테이블과 1:1.
// created_at/updated_at(자동)은 제외. media_id는 등록 시 필수, 수정 시 읽기전용.

export type MediaFieldType = "text" | "number" | "textarea" | "boolean" | "json";

export interface MediaFieldDef {
  key: string;
  label: string;
  type: MediaFieldType;
}

export const MEDIA_ID_FIELD: MediaFieldDef = {
  key: "media_id",
  label: "매체 ID",
  type: "text",
};

// grid-2 로 나열되는 나머지 전 컬럼 (media_id 제외)
export const MEDIA_FIELDS: MediaFieldDef[] = [
  { key: "name", label: "매체명", type: "text" },
  { key: "second_name", label: "보조명", type: "text" },
  { key: "building_name", label: "건물명", type: "text" },
  { key: "media_source", label: "매체 출처", type: "text" },
  { key: "sales_type", label: "판매 유형", type: "text" },
  { key: "ooh_type", label: "OOH 유형", type: "text" },
  { key: "exposure_type", label: "노출 유형", type: "text" },
  { key: "device_type", label: "디바이스 유형", type: "text" },
  { key: "media_shape", label: "매체 형태", type: "text" },
  { key: "media_shape_summary", label: "매체 형태 요약", type: "textarea" },
  { key: "category_large", label: "카테고리(대)", type: "text" },
  { key: "category_small", label: "카테고리(소)", type: "text" },
  { key: "category_id", label: "카테고리 ID", type: "number" },
  { key: "parent_category_code", label: "상위 카테고리 코드", type: "text" },
  { key: "loc_code", label: "지역 코드", type: "text" },
  { key: "loc_label", label: "지역 표시명", type: "text" },
  { key: "city", label: "시/도", type: "text" },
  { key: "district", label: "구/군", type: "text" },
  { key: "market_area", label: "상권명", type: "text" },
  { key: "market_dong", label: "상권 동", type: "text" },
  { key: "legal_dong", label: "법정동", type: "text" },
  { key: "market_profile_id", label: "상권 프로파일 ID", type: "number" },
  { key: "market_keyword", label: "상권 키워드", type: "text" },
  { key: "address", label: "주소", type: "text" },
  { key: "address_detail", label: "상세 주소", type: "text" },
  { key: "accurate_address", label: "정확한 주소", type: "text" },
  { key: "full_address_jibun", label: "지번 주소", type: "text" },
  { key: "moving_location_detail", label: "이동 위치 상세", type: "text" },
  { key: "latitude", label: "위도", type: "number" },
  { key: "longitude", label: "경도", type: "number" },
  { key: "audience_summary", label: "타깃 요약", type: "textarea" },
  { key: "min_advertisement_fee_krw", label: "최소 광고비(원)", type: "number" },
  { key: "max_advertisement_fee_krw", label: "최대 광고비(원)", type: "number" },
  { key: "min_production_fee_krw", label: "최소 제작비(원)", type: "number" },
  { key: "max_production_fee_krw", label: "최대 제작비(원)", type: "number" },
  { key: "any_production_fee_yn", label: "제작비 유무", type: "boolean" },
  { key: "production_fees_summary", label: "제작비 요약", type: "textarea" },
  { key: "plan_count", label: "플랜 수", type: "number" },
  { key: "execution_status", label: "집행 상태", type: "text" },
  { key: "lead_time_bizdays", label: "리드타임(영업일)", type: "number" },
  { key: "device_quantity", label: "디바이스 수량", type: "number" },
  { key: "surface_quantity", label: "표면 수량", type: "number" },
  { key: "properties_count", label: "속성 수", type: "number" },
  { key: "properties_summary", label: "속성 요약", type: "textarea" },
  { key: "properties_type", label: "속성 유형", type: "text" },
  { key: "properties_extra_json", label: "속성 추가정보(JSON)", type: "json" },
  { key: "final_grade", label: "최종 등급", type: "text" },
  { key: "feature", label: "특징", type: "text" },
  { key: "quality_score", label: "품질 점수", type: "number" },
  { key: "gangnam_dong_grade", label: "강남 동 등급", type: "text" },
  { key: "gangnam_grade_reason", label: "강남 등급 사유", type: "textarea" },
  { key: "grade_method", label: "등급 산정 방식", type: "text" },
  { key: "grade_evidence", label: "등급 근거", type: "textarea" },
  { key: "area_evidence", label: "지역 근거", type: "textarea" },
  { key: "ind_evidence", label: "업종 근거", type: "textarea" },
  { key: "thumbnail_url", label: "대표 이미지 URL", type: "text" },
  { key: "image_count", label: "이미지 수", type: "number" },
  { key: "is_newly_built_yn", label: "신축 여부", type: "boolean" },
  { key: "is_popular_yn", label: "인기 여부", type: "boolean" },
  { key: "popular_type", label: "인기 유형", type: "text" },
  { key: "special_remarks", label: "특이사항", type: "textarea" },
  { key: "description", label: "설명", type: "textarea" },
  { key: "children_count", label: "하위 매체 수", type: "number" },
  { key: "road_view_heading", label: "로드뷰 방향", type: "number" },
  { key: "road_view_latitude", label: "로드뷰 위도", type: "number" },
  { key: "road_view_longitude", label: "로드뷰 경도", type: "number" },
  { key: "road_view_pitch", label: "로드뷰 피치", type: "number" },
  { key: "markers_vo", label: "마커 정보(JSON)", type: "json" },
  { key: "map_bounds_vo", label: "지도 경계(JSON)", type: "json" },
  { key: "recommended_media_items", label: "추천 매체(JSON)", type: "json" },
  { key: "list_labels", label: "리스트 라벨(JSON)", type: "json" },
  { key: "source_detail_id", label: "원본 상세 ID", type: "number" },
  { key: "company_media_id", label: "회사 매체 ID", type: "number" },
  { key: "company_mapper_user_id", label: "회사 매퍼 사용자 ID", type: "number" },
  { key: "source_created_at", label: "원본 생성일시", type: "text" },
  { key: "source_updated_at", label: "원본 수정일시", type: "text" },
];
